version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: devdbuser
      WORDPRESS_DB_PASSWORD: devdbpass
      WORDPRESS_DB_NAME: devdb
    volumes:
       - ./wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: devdb
      MYSQL_USER: devdbuser
      MYSQL_PASSWORD: devdbpass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./data:/var/lib/mysql
