blank_issues_enabled: true
contact_links:
  - name: OBFF Crew
    url: https://ohiobarn.github.io/flowerfarm/crew/
    about: Home for the OBFF crew. Go here for instructions and other crew resources.
